name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    env:
      PRE_COMMIT_HOME: ~/.cache/pre-commit

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Cache pre-commit
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pre-commit-${{ matrix.python-version }}-
          ${{ runner.os }}-pre-commit-

    - name: Install uv
      run: pip install uv

    - name: Install dependencies
      run: |
        uv pip install -r requirements.txt

    - name: Install ruff
      run: uv pip install ruff

    - name: Install pre-commit
      run: uv pip install pre-commit

    - name: Run pre-commit (lint/format)
      run: pre-commit run --all-files --show-diff-on-failure

    - name: Run Tests with coverage
      run: |
        pytest --cov=. --cov-report=xml --cov-report=term

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-${{ matrix.python-version }}
        path: coverage.xml
